Hw8: done
Xiatelly/java_lessons pull request #6
Opened 2024-03-03 16:02 UTC by Xiatelly

2024-03-11 19:26 UTC, pipekalo requested changes

2024-03-11 19:26 UTC, pipekalo commented on hw8/src/FileNavigator.java
> +    public void validatePath(){
логичнее это встроить сразу в метод добавления

2024-03-11 19:26 UTC, pipekalo commented on hw8/src/FileNavigator.java
> +        if (record == null){
это можно схлопнуть(упростить) в готовый метод интерфейса Map

2024-03-11 19:26 UTC, pipekalo commented on hw8/src/FileNavigator.java
> +    public final HashMap<String, List<FileData>> getData() {
а зачем тебе тут final?  ты наверное хочешь данные защитить? то тогда лучше создавать клон-копию и возвращать её, а так ты просто отдала указатель который вне класса не должен нигде быть

2024-03-11 19:26 UTC, pipekalo commented on hw8/src/FileNavigator.java
> +    public final HashMap<String, List<FileData>> getData() {
Final для метода это просто запрет на переопределение

2024-03-17 18:12 UTC, Xiatelly commented on hw8/src/FileNavigator.java
> +    public void validatePath(){
Ну у меня же и так метод добавления консистентный, он не может быть неконсистентным, поэтому и писала отдельно тот метод для проверки. Собственно и в слак с подобным вопросом вылазила по такому же "поводу".

2024-03-25 17:22 UTC, pipekalo commented on hw8/src/FileNavigator.java
> +    public void validatePath(){
ну просто потому что используется всего в одном месте, хотя можешь оставить так это уже сугубо на любителя

2024-04-01 18:34 UTC, merged